### ISSUE TITLE
Descriptive error when .from_() call is omitted

### ISSUE THREAD

**Issue by butla** [kayak/pypika#140]
I just spent some time figuring out what happened when I transcribed a slightly comples query from raw SQL to pypika (this is a great library, BTW!). The error I was getting was quite cryptic:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/butla/.virtualenvs/bla-Y9MmHOr2/lib/python3.6/site-packages/pypika/queries.py", line 161, in select
    return cls._builder().select(*terms)
  File "/home/butla/.virtualenvs/bla-Y9MmHOr2/lib/python3.6/site-packages/pypika/utils.py", line 46, in _copy
    result = func(self_copy, *args, **kwargs)
  File "/home/butla/.virtualenvs/bla-Y9MmHOr2/lib/python3.6/site-packages/pypika/queries.py", line 379, in select
    self._select_field_str(term)
  File "/home/butla/.virtualenvs/bla-Y9MmHOr2/lib/python3.6/site-packages/pypika/queries.py", line 565, in _select_field_str
    self._select_field(Field(term, table=self._from[0]))
IndexError: list index out of range
list index out of range
```

Turns out I forgot to add `from_()` call.

**Steps to reproduce:**
run `Query.select('asdf')`

**Comment by twheys** [comment]
Thanks for reporting this issue. Will add a fix for it soon.

**Comment by svenberkvens** [comment]
Should be possible, though? At least PostgreSQL supports queries like:

SELECT 1+2

and returns one row with one column containing 3.

**Comment by twheys** [comment]
@svenberkvens you're right, and that does work in pypika currently, but in @butla 's case he is trying to select from a Field, which wouldn't be possible if you aren't selecting from a table. I'll have that raise an exception.
