### ISSUE TITLE
MySQL > PseudoColumns > 'PseudoColumn' object has no attribute 'alias'

### ISSUE THREAD

**Issue by wildtron** [kayak/pypika#241]
Issue:
1.  `PseudoColumn` used in conjunction with `orderby` raises an AttributeError

To reproduce:
```python
>>> from pypika import JoinType, Table, functions as fn
>>> from pypika.dialects import MySQLQuery as Query
>>> from pypika.terms import PseudoColumn
>>> from datetime import date

>>> p = Table('sample', alias='p')
>>> q = Table('sample_2', alias='q')

>>> Query.from_(p).join(q).on(p.id == q.id).select(p.id, p.foo, q.bar).get_sql()
'SELECT `p`.`id`,`p`.`foo`,`q`.`bar` FROM `sample` `p` JOIN `sample_2` `q` ON `p`.`id`=`q`.`id`'

# orderby works fine here
>>> Query.from_(p).join(q).on(p.id == q.id).select(p.id, p.foo, q.bar).orderby(p.id).get_sql()
'SELECT `p`.`id`,`p`.`foo`,`q`.`bar` FROM `sample` `p` JOIN `sample_2` `q` ON `p`.`id`=`q`.`id` ORDER BY `p`.`id`'

# PseudoColumn and orderby used in conjunction
>>> Query.from_(p).join(q).on(p.id == q.id).select(PseudoColumn("'{}'".format(date(2019, 1, 1))),p.id, p.foo, q.bar).orderby(p.id).get_sql()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/pypika/dialects.py", line 42, in get_sql
    querystring = super(MySQLQueryBuilder, self).get_sql(with_alias, subquery, **kwargs)
  File "/usr/lib/python3.7/site-packages/pypika/queries.py", line 825, in get_sql
    querystring += self._orderby_sql(**kwargs)
  File "/usr/lib/python3.7/site-packages/pypika/queries.py", line 947, in _orderby_sql
    selected_aliases = {s.alias for s in self._selects}
  File "/usr/lib/python3.7/site-packages/pypika/queries.py", line 947, in <setcomp>
    selected_aliases = {s.alias for s in self._selects}
AttributeError: 'PseudoColumn' object has no attribute 'alias'
>>> 
```

Other considerations:
1. dialect used is MySQL

**Comment by wildtron** [comment]
Found a work-around. Using `terms.ValueWrapper` could make an alternative solution for this.

**Comment by twheys** [comment]
Not sure why you need to use either of those classes directly. Try just selecting the raw date without formatting it or wrapping it. Pypika should handle it for you. Let me know if you have any issues.
