### ISSUE TITLE
error in where construct when using db-definition

### ISSUE THREAD

**Issue by popokatapepel** [kayak/pypika#370]
When i use the following code to generate a simple query with a where clause, the output is correct and everythin is working fine:

```
customers = Table('customers')
q = Query.from_(customers).select(
    customers.id, customers.fname, customers.lname, customers.phone
).where(
    customers.lname == 'Mustermann'
)
```

However, when i define the db first and the table inside the db, i get an Attribute error `AttributeError: 'bool' object has no attribute 'fields_'`

```
db = Database('some_db')
customers = db.customers 
q = Query.from_(customers).select(
    customers.id, customers.fname, customers.lname, customers.phone
).where(
    customers.lname == 'Mustermann'
)
```

with the following exception stack:

```
Traceback (most recent call last):
  File "C:\...\test.py", line 10, in <module>
    customers.lname == 'Mustermann'
  File "C:\...\venv\lib\site-packages\pypika\utils.py", line 48, in _copy
    result = func(self_copy, *args, **kwargs)
  File "C:\...\venv\lib\site-packages\pypika\queries.py", line 772, in where
    if not self._validate_table(criterion):
  File "C:\...\venv\lib\site-packages\pypika\queries.py", line 982, in _validate_table
    for field in term.fields_():
AttributeError: 'bool' object has no attribute 'fields_'
```

**Comment by popokatapepel** [comment]
my mistake. when I define db as a `Schema`, everything works as expected

````
db = Schema('some_db')
customers = db.customers 
q = Query.from_(customers).select(
    customers.id, customers.fname, customers.lname, customers.phone
).where(
    customers.lname == 'Mustermann'
)
```
