### ISSUE TITLE
Working around python's recursion limit when generating queries with many where conditions

### ISSUE THREAD

**Issue by khalilfazal** [kayak/pypika#480]
Hi, I'm trying to get the following to work:

```python
from pypika import Criterion, Table, Query

table = Table('Table')
limit = 1000
criteria = [table.field == i for i in range(limit)]

q = Query \
    .from_(t) \
    .select('*') \
    .where(Criterion.any(criteria)) \
    .get_sql()

print(q)
```

It produces the following:

```
Traceback (most recent call last):
  File "./test.py", line 8, in <module>
    q = Query \
  File "~/.local/lib/python3.8/site-packages/pypika/utils.py", line 50, in _copy
    result = func(self_copy, *args, **kwargs)
  File "~/.local/lib/python3.8/site-packages/pypika/queries.py", line 868, in where
    if not self._validate_table(criterion):
  File "~/.local/lib/python3.8/site-packages/pypika/queries.py", line 1096, in _validate_table
    for field in term.fields_():
  File "~/.local/lib/python3.8/site-packages/pypika/terms.py", line 74, in fields_
    return set(self.find_(Field))
  File "~/.local/lib/python3.8/site-packages/pypika/terms.py", line 54, in find_
    return [node for node in self.nodes_() if isinstance(node, type)]
  File "~/.local/lib/python3.8/site-packages/pypika/terms.py", line 54, in <listcomp>
    return [node for node in self.nodes_() if isinstance(node, type)]
  File "~/.local/lib/python3.8/site-packages/pypika/terms.py", line 670, in nodes_
    yield from self.left.nodes_()
  [Previous line repeated 987 more times]
  File "~/.local/lib/python3.8/site-packages/pypika/terms.py", line 669, in nodes_
    yield from self.right.nodes_()
  File "~/.local/lib/python3.8/site-packages/pypika/terms.py", line 670, in nodes_
    yield from self.left.nodes_()
  File "~/.local/lib/python3.8/site-packages/pypika/terms.py", line 479, in nodes_
    yield from self.table.nodes_()
RecursionError: maximum recursion depth exceeded
```

Could this be done without recursion? Is there a work-around for this?
Do I need to somehow use the `ignore_copy()` decorator?

**Comment by mikeengland** [comment]
Hi @khalilfazal. You can change the recursion limit in Python using `sys.setrecursionlimit(1500)`, however, that protection is there for a reason.

I suggest looking at your query again and figuring out if there is a better way you can do this. For example, given you are creating where clauses from [0..limit - 1] in a sequential fashion, why do you not do the following:
`select * from table where field between 0 and <limit - 1>`?

I'll close this for now as it isn't an issue with PyPika itself.
