### ISSUE TITLE
Postgres `on_conflict` doesn't work

### ISSUE THREAD

**Issue by elmehalawi** [kayak/pypika#567]
I copied this code from the readme file:

```python
customers = Table('customers')

q = Query.into(customers)\
    .insert(1, 'Jane', 'Doe', 'jane@example.com')\
    .on_conflict(customers.email)
    .do_update(customers.email, 'bob@example.com')
```

When I run this code, I get the following error:

> Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/hassan/Documents/importer/importer.py", line 140, in upload_endpoint
    import_users(path, "1234")
  File "/Users/hassan/Documents/importer/importer.py", line 106, in import_users
    Query.into(customers)
TypeError: 'Field' object is not callable

I'm using pypika version 0.47.7

**Comment by waydegg** [comment]
"ON CONFLICT" seems to only be supported by the `PostgreSQLQueryBuilder`, so to have Pypika recognize that `.on_conflict()` isn't a field you should import Query as `from pypika import PostgreSQLQuery as Query`. I'm not sure if the other relational databases support that clause, but if they do it's not supported in the latest version of Pypika (0.48.8).
