### ISSUE TITLE
Installation of the latest version version fails

### ISSUE THREAD

**Issue by GilZ** [kayak/pypika#85]
Steps to reproduce:
```
pip install pypika==0.9.2
```
Output:
```
Collecting pypika==0.9.2
  Downloading PyPika-0.9.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ho1zhl5j/pypika/setup.py", line 35, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ho1zhl5j/pypika/
```

This is a regression from previous patch version:
```
pip install pypika==0.9.1
```
Output:
```
Collecting aenum (from pypika==0.9.1)
  Downloading aenum-2.0.9-py3-none-any.whl
Installing collected packages: aenum
  Found existing installation: aenum 2.0.8
    Uninstalling aenum-2.0.8:
      Successfully uninstalled aenum-2.0.8
Successfully installed aenum-2.0.9
```

I'm using Anaconda 4.3.29 (Python 3.6.3) on Ubuntu 16.04

**Comment by mikeengland** [comment]
Thank you very much for the detailed explanation @GilZ.

0.9.3 will be released shortly which will fix this.

**Comment by mikeengland** [comment]
@GilZ Version 0.9.3 is now released. Thanks again 👍
